### ISSUE TITLE
Jpype1-py3 디펜던시

### ISSUE THREAD

**Issue by daewonyoon** [theeluwin/lexrankr#2]
jpype1-py3 디펜던시가 필요한가요?

konlpy 를 설치할 때, jpype1 을 설치한 파이썬3 환경에서 (윈도우)

     pip install lexrankr

을 실행하면, jpype1-py3 를 설치하다가 설치가 실패하네요.

소스를 받아서 setup.py 에서 jpype1-py3 부분을 삭제하면 설치가 됩니다.

**Comment by theeluwin** [comment]
jpype1-py3 없이도 konlpy가 문제 없이 동작 하나요? 그렇다면 없애도 될거같긴 합니다 (본 레포에선 jpype1이 필요하다기보단 konlpy가 필요합니다).

**Comment by daewonyoon** [comment]
네. Konlpy  를 어찌어찌 설치하여 동작이 확인된 파이썬3 환경에서 pip install lexrankr 하면 jpype1-py3 설치하며 컴파일러가 없어 에러가 발생합니다.

**Comment by theeluwin** [comment]
윈도우의 경우 jpype 관련은 별도로 설치하는 것으로 변경되었습니다. a6fd9114ac62e2870ef9281f0190b594c7d1cb55
