### ISSUE TITLE
Installation error for MacOS

### ISSUE THREAD

**Issue by shim0494** [theeluwin/lexrankr#3]
ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-ua7uw3bh/jpype1-py3_b5f67a7ac7cb485f8031edeca38b4e3b/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-ua7uw3bh/jpype1-py3_b5f67a7ac7cb485f8031edeca38b4e3b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-xwnug4o9/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/jpype1-py3
         cwd: /private/tmp/pip-install-ua7uw3bh/jpype1-py3_b5f67a7ac7cb485f8031edeca38b4e3b/
    Complete output (60 lines):
    
    ********* DEPRECATION WARNING *********
    Warning: This version of JPype is now deprecated, see issue #29 for more details
    Warning:     https://github.com/tcalmant/jpype-py3/issues/29
    Warning:
    Warning: Please use this version instead:
    Warning:     https://github.com/jpype-project/jpype
    Warning:
    Warning: It can be installed using:
    Warning:     pip install JPype1
    ********* DEPRECATION WARNING *********
    
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.9
    creating build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_jcollection.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_pykeywords.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_jproxy.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_gui.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_darwin.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/nio.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_cygwin.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_properties.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_refdaemon.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/JClassUtil.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_jvmfinder.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_core.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_linux.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_jarray.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_jobject.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_jclass.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_windows.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_jwrapper.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_jexception.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/reflect.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    copying jpype/_jpackage.py -> build/lib.macosx-10.9-x86_64-3.9/jpype
    creating build/lib.macosx-10.9-x86_64-3.9/jpype/awt
    copying jpype/awt/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/jpype/awt
    creating build/lib.macosx-10.9-x86_64-3.9/jpype/awt/event
    copying jpype/awt/event/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/jpype/awt/event
    copying jpype/awt/event/WindowAdapter.py -> build/lib.macosx-10.9-x86_64-3.9/jpype/awt/event
    creating build/lib.macosx-10.9-x86_64-3.9/jpypex
    copying jpypex/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/jpypex
    creating build/lib.macosx-10.9-x86_64-3.9/jpypex/swing
    copying jpypex/swing/AbstractAction.py -> build/lib.macosx-10.9-x86_64-3.9/jpypex/swing
    copying jpypex/swing/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/jpypex/swing
    copying jpypex/swing/pyutils.py -> build/lib.macosx-10.9-x86_64-3.9/jpypex/swing
    running build_ext
    building '_jpype' extension
    creating build/temp.macosx-10.9-x86_64-3.9
    creating build/temp.macosx-10.9-x86_64-3.9/native
    creating build/temp.macosx-10.9-x86_64-3.9/native/common
    creating build/temp.macosx-10.9-x86_64-3.9/native/python
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -DMACOSX=1 -Inative/common/include -Inative/python/include -I/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home/include/darwin -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c native/common/jp_array.cpp -o build/temp.macosx-10.9-x86_64-3.9/native/common/jp_array.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-ua7uw3bh/jpype1-py3_b5f67a7ac7cb485f8031edeca38b4e3b/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-ua7uw3bh/jpype1-py3_b5f67a7ac7cb485f8031edeca38b4e3b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-xwnug4o9/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/jpype1-py3 Check the logs for full command output.

**Comment by theeluwin** [comment]
Removed (no longer necessary) `jpype1-py3` dependency in 157e073a77f7197e880a7a288687e4179853aa56.
